-- 업무도구 통합 게시판 테이블 생성
CREATE TABLE IF NOT EXISTS work_tool_boards (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  board_type TEXT NOT NULL CHECK (board_type IN ('SOP', 'TOOLS', 'TROUBLESHOOTING', 'TECH_DATA')),
  title TEXT NOT NULL,
  content TEXT NOT NULL,
  author_id TEXT NOT NULL,
  author_name TEXT NOT NULL,
  views INTEGER DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- RLS (Row Level Security) 설정
ALTER TABLE work_tool_boards ENABLE ROW LEVEL SECURITY;

-- 읽기 권한: 누구나 읽기 가능 (API 서버에서 권한 검증)
CREATE POLICY "모든 사용자가 읽기 가능" 
ON work_tool_boards FOR SELECT 
USING (true);

-- 쓰기 권한: 누구나 작성 가능 (API 서버에서 권한 검증)
CREATE POLICY "모든 사용자가 작성 가능" 
ON work_tool_boards FOR INSERT 
WITH CHECK (true);

-- 수정 권한: (API 서버에서 권한 검증)
CREATE POLICY "모든 사용자가 수정 가능" 
ON work_tool_boards FOR UPDATE 
USING (true);

-- 삭제 권한: (API 서버에서 권한 검증)
CREATE POLICY "모든 사용자가 삭제 가능" 
ON work_tool_boards FOR DELETE 
USING (true);

-- 인덱스 추가 (조회 성능 최적화)
CREATE INDEX IF NOT EXISTS idx_work_tool_boards_type ON work_tool_boards(board_type);
CREATE INDEX IF NOT EXISTS idx_work_tool_boards_created ON work_tool_boards(created_at DESC);
