-- 게시판 댓글 테이블 생성
CREATE TABLE IF NOT EXISTS board_comments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  board_id BIGINT NOT NULL REFERENCES work_tool_boards(id) ON DELETE CASCADE,
  author_id TEXT NOT NULL,
  author_name TEXT NOT NULL,
  content TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- RLS 설정
ALTER TABLE board_comments ENABLE ROW LEVEL SECURITY;

-- 읽기: 누구나
CREATE POLICY "댓글 읽기 가능"
ON board_comments FOR SELECT
USING (true);

-- 쓰기: 누구나 (API 서버에서 인증 검증)
CREATE POLICY "댓글 작성 가능"
ON board_comments FOR INSERT
WITH CHECK (true);

-- 삭제: 누구나 (API 서버에서 권한 검증)
CREATE POLICY "댓글 삭제 가능"
ON board_comments FOR DELETE
USING (true);

-- 인덱스
CREATE INDEX IF NOT EXISTS idx_board_comments_board_id ON board_comments(board_id);
CREATE INDEX IF NOT EXISTS idx_board_comments_created ON board_comments(created_at);
